name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.8", "3.10", "3.12"]
        torch: ["2.0", "2.2", "2.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: |
          pip install -e .[test]

      - name: Test
        run: |
          ruff .
          pytest --cov --cov-report term-missing --cov-fail-under 80 tests/
          mypy
